"""add deleted property

Revision ID: 53704db97fbd
Revises: 8d568c4f38f5
Create Date: 2019-10-11 20:36:23.403531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53704db97fbd'
down_revision = '8d568c4f38f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
