"""set deleted unnullable

Revision ID: 618bce7ede69
Revises: 53704db97fbd
Create Date: 2019-10-11 20:40:46.463531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618bce7ede69'
down_revision = '53704db97fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
