"""update order model

Revision ID: 8d568c4f38f5
Revises: bb73079f9293
Create Date: 2019-10-09 21:32:14.612431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d568c4f38f5'
down_revision = 'bb73079f9293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_address', 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_address', type_='foreignkey')
        batch_op.drop_column('address_id')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
